### ISSUE TITLE
call for help

### ISSUE THREAD

**Issue by chuakyang** [AntiAegis/Image-Forgery-using-Deep-Learning#1]
can you give us the link to your paper about this project

**Comment by AntiAegis** [comment]
Hi @chuakyang,

Currently, for some reasons, I cannot show you the paper. However, I updated README.md so that you can have more information about our project. I will give you the link to the paper when I can. Thanks for your attention.

**Comment by chuakyang** [comment]
Thank you for your reply. I'll keep eyes on your homepage.

**Comment by AntiAegis** [comment]
Now you can check out our [technical report](https://github.com/AntiAegis/Image-Forgery-using-Deep-Learning/blob/master/README.md#technical-report) for further information.

**Comment by chuakyang** [comment]
Thank you for informing me. I will read your paper carefully.

**Comment by titikid** [comment]
@AntiAegis the link for paper was broken. How can i get it?
