### ISSUE TITLE
"Prediction: Positive ==> True"

### ISSUE THREAD

**Issue by liuzheng081** [AntiAegis/Image-Forgery-using-Deep-Learning#2]
Hi,
i run the demo/compare-prediction.ipynb and i have no idea about 
![image](https://user-images.githubusercontent.com/10113362/53789969-b81f9a80-3f60-11e9-80a7-8a722a12dc49.png)
like "Prediction: Positive ==> True"  it means the pic is authentic?
and "Prediction: Positive ==> False" it means the pic is tampering?

**Comment by AntiAegis** [comment]
Prediction: Positive ==> True" means: The model predicts image as Positive (the image is tampered) and the ground truth is also Positive. So the prediction is True.

Prediction: Positive ==> False" means: The model predicts image as Positive (the image is tampered) but the ground truth is Negative. So the prediction is False.

**Comment by liuzheng081** [comment]
> Prediction: Positive ==> True" means: The model predicts image as Positive (the image is tampered) and the ground truth is also Positive. So the prediction is True.
> 
> Prediction: Positive ==> False" means: The model predicts image as Positive (the image is tampered) but the ground truth is Negative. So the prediction is False.

that means just use decision == 1 can know the image is tampered or not?

**Comment by AntiAegis** [comment]
(decision==1) ===> Positive ===> Tampered image
(decision==0) ===> Negative ===> Authentic image

**Comment by liuzheng081** [comment]
> (decision==1) ===> Positive ===> Tampered image
> (decision==0) ===> Negative ===> Authentic image

Thank you
