### ISSUE TITLE
i have no idea about Positive and Negative 

### ISSUE THREAD

**Issue by yisampi** [AntiAegis/Image-Forgery-using-Deep-Learning#3]
@AntiAegis , i have no idea about below code, and i don't know how to predict a new image tampered?
if decision==1:
    if GT=="Positive":
        print("Prediction: Positive ==> True")
    else:
        print("Prediction: Positive ==> False")
else:
    if GT=="Positive":
        print("Prediction: Negative ==> False")
    else:
        print("Prediction: Negative ==> True")

**Comment by AntiAegis** [comment]
You can check the answer in here #2
