### ISSUE TITLE
about the model

### ISSUE THREAD

**Issue by liuzheng081** [AntiAegis/Image-Forgery-using-Deep-Learning#4]
Hi, 
i tried the model with demo/compare-prediction.ipynb use our  tamper image data . but the result is not good .
can you help me how to fineturn with your model in the project

**Comment by AntiAegis** [comment]
As mentioned in the [technical report](https://github.com/AntiAegis/Image-Forgery-using-Deep-Learning#technical-report), we trained models using the CASIA2 dataset. Therefore, we just limit the scope of the project in this dataset for benchmarking. 

If you test images come from the CASIA2 dataset, the performance will be acceptable. In the case of another dataset (i.e., your prepared dataset), the distribution may be different from one of CASIA2. Thus,  if you want to make the model more generalized, you should try to train it with more data.
