### ISSUE TITLE
Foregeryb detection test 

### ISSUE THREAD

**Issue by fatiha92** [AntiAegis/Image-Forgery-using-Deep-Learning#5]
Hello,

I want to test this project but I do not know how to do it (I'm beginanate), you can help me please? I consulted the technical report but it is empty.

thanks in advance

**Comment by AntiAegis** [comment]
What do you want to test? Please tell us more clearly so that we can help you!
Regarding the technical report, it is still there: https://github.com/AntiAegis/Image-Forgery-using-Deep-Learning/blob/master/thuy2018.pdf

**Comment by fatiha92** [comment]
Yes I have access to this article. My question is, how can I test the code on my machine?

**Comment by AntiAegis** [comment]
In the demo folder (https://github.com/AntiAegis/Image-Forgery-using-Deep-Learning/tree/master/demo), you can find jupyter files for testing. To run jupyter, you need to read this site: https://jupyter.org

**Comment by fatiha92** [comment]
I thank you for your answer. I have another question, I want to test an image that is in my database, in which folder should I put it????

**Comment by AntiAegis** [comment]
For example, you run the file https://github.com/AntiAegis/Image-Forgery-using-Deep-Learning/blob/master/demo/test-MBN2-mod-YCbCr.ipynb for testing, you can modify folder path in the "Initial procedure" to be compatible with your computer.

**Comment by fatiha92** [comment]
Thank you so much for your replay

**Comment by fatiha92** [comment]
Sorry to bother you but I have not found where load my image to test it, can you help me with more details, please?
